### ISSUE TITLE
Android doesn't render the list

### ISSUE THREAD

**Issue by rborn** [asciiman/react-native-native-listview#2]
I tried to test on android and the list doesn't seem to get rendered.
Maybe I'm not setting up the `createReactInstanceManager` in the right place?

Thank you.

**Comment by rborn** [comment]
Ok, I got it, the list needs to have `flex:1` in style.

I can make a PR to the Readme if you want

**Comment by asciiman** [comment]
Hmm... interesting.  It works on my app on android without `flex: 1` in the list.  Having the flex in the parent View was sufficient.

**Comment by rborn** [comment]
I'll try to make a testcase

**Comment by rborn** [comment]
Ok, here is the test case: 

If I remove any flex style in the render function, the list won't show up anymore on android.
It's android 4.4.4.

~~~
class ListExample extends Component {
    render() {
        return (
            <View style={{ flex: 1 }}>
                <NativeListview
                    renderRow={this.renderRow}
                    numRows={dataSource.length}
                    rowHeight={75}
                    style={{ flex: 1 }}
                />
            </View>
        );
    }
    renderRow(rowID) {
        return (
            <View style={styles.container}>
                <Text style={{ width: 100, height: 50 }}>{dataSource[rowID]}</Text>
                <Text style={styles.red}>{dataSource[rowID]}</Text>
                <Image style={{ width: 100, height: 75 }} source={{ uri: 'https://unsplash.it/100/75?image=' + rowID }} />
            </View>
        );
    }
}
~~~
