### ISSUE TITLE
Android - rowID doesn't seem to be sent correctly to js

### ISSUE THREAD

**Issue by rborn** [asciiman/react-native-native-listview#3]
The list works great, but the content of the rows on scroll is not the correct one. It looks like `rowId` is not passed at all to the [onUpateView](https://github.com/asciiman/react-native-native-listview/blob/master/src/item.android.js#L19)

**Comment by rborn** [comment]
Update - I made the onUpdateView  an empty function and the results is the same, I guess there is an issue on the native side :(

**Comment by asciiman** [comment]
This should be fixed in 1.2.0.  Can you try it out?

**Comment by rborn** [comment]
ASAP 🙇

**Comment by rborn** [comment]
Ok, this seems to work correctly now, thank you
